#cloud-config

package_update: true
package_upgrade: true

packages:
  - python3
  - python3-pip
  - nodejs
  - zip
  - unzip
  - python3-venv
  - npm

runcmd:
  - echo "Setup complete!" > /var/log/cloud-init-custom.log
