apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-assignment-backend
spec:
  selector:
    matchLabels:
      app: k8-assignment-backend
  template:
    metadata:
      labels:
        app: k8-assignment-backend
    spec:
      containers:
      - name: k8-assignment-backend
        image: docker.io/gurbakshkaur/k8-asign-backend:latest
        ports:
        - containerPort: 5000

--- 
apiVersion: v1
kind: Service
metadata:
  name: k8-assignment-backend
spec:
  selector:
    app: k8-assignment-backend
  ports:
  - port: 80
    targetPort: 5000
